apiVersion: v1
kind: Service
metadata:
  name: sargam-analytics-service
spec:
  selector:
    app: sargam-analytics
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sargam-analytics
spec:
  selector:
    matchLabels:
      app: sargam-analytics
  replicas: 4
  template:
    metadata:
      labels:
        app: sargam-analytics
    spec:
      containers:
      - name: sargam-analytics
        image: sargam-analytics
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
